site_name: Geograypher Documentation
theme:
  name: material
  logo: assets/logo-shaded.png
  favicon: assets/logo.png
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.instant
    - navigation.indexes
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    - content.action.edit
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      accent: lime

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - toc:
      permalink: true

plugins:
  - search
  - mkdocs-nav-weight:
      section_renamed: false
      index_weight: -10
      warning: true
      reverse: false
      headless_included: false
  - awesome-pages
  - git-revision-date-localized:
        enable_creation_date: true
  - git-committers:
      repository: open-forest-observatory/geograypher
      branch: main
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          selection:
            members_order: 'source' 
          options:
            heading_level: 2
            show_root_heading: true
            show_root_full_path: false
            show_category_heading: true
            show_root_toc_entry: false
            show_symbol_type_heading: true
            show_symbol_type_toc: true            

nav:
  - "← OFO home": https://openforestobservatory.org/
  - ...

repo_url: https://github.com/open-forest-observatory/geograypher
repo_name: open-forest-observatory/geograypher
edit_uri: edit/main/docs/