[tool.poetry]
name = "semantic-mesh-pytorch3d"
version = "0.1.0"
description = ""
authors = ["David Russell <davidrussell327@gmail.com>"]
readme = "README.md"
packages = [{include = "semantic_mesh_pytorch3d"}]

[tool.poetry.dependencies]
python = ">=3.9,<3.13"
geopandas = "^0.14.0"
pyvista = "^0.42.2"
scipy = "^1.11.2"
imageio = "^2.31.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
