[tool.poetry]
name = "multiview-prediction-toolkit"
version = "0.1.0"
description = ""
authors = ["David Russell <davidrussell327@gmail.com>"]
readme = "README.md"
packages = [{include = "multiview_prediction_toolkit"}]

[tool.poetry.dependencies]
python = ">=3.9,<3.12"
pyvista = "^0.42.2"
scikit-image = "^0.21.0"
piexif = "^1.1.3"
rastervision = "^0.21.3"
chardet = "^5.2.0"
ipykernel = "^6.26.0"
trame = "^3.2.8"
rasterstats = "^0.19.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
