name: Black Linter

on:
  workflow_run:
    workflows: [Isort Linter]
    types:
      - completed

jobs:
  black-linter:
    name: Run Black
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Pull latest changes
        run: git pull origin ${{ github.ref }}

      - name: Run Black formatter
        uses: psf/black@stable
        with:
          options: "--verbose"
          src: "."
          jupyter: true

      - name: Determine Branch Name
        run: |
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            echo "BRANCH_NAME=${{ github.head_ref }}" >> $GITHUB_ENV
          else
            BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/})
            echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV
          fi

      - name: Push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Apply formatting changes
          branch: ${{ env.BRANCH_NAME }}